Refactored to use proper OOP principles
Borgerr/chaos pull request #6
Opened 2023-11-09 02:05 UTC by F1scherman

2023-11-09 02:09 UTC, coravacav requested changes

2023-11-09 02:09 UTC, coravacav commented on src/dice_builder_builder.rs
> +    }
You should take self here, so
- it's harder to call
- you need to own it fully

2023-11-09 04:32 UTC, Borgerr commented
lgtm

2023-11-09 04:32 UTC, merged

2023-11-11 21:33 UTC, ChaseParate commented
Lol, lmao even